map:
  # 1. No metadata provided at all: should use the key as the name.
  my-app:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
            - name: my-container
              image: nginx:latest

  # 2. Metadata provided with an explicit name.
  custom-service:
    apiVersion: v1
    kind: Service
    metadata:
      name: explicit-service-name
      labels:
        app: my-app
    spec:
      selector:
        app: my-app
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80

  # 3. Metadata provided without a name: should default to the key.
  my-config:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: test
    data:
      key1: value1

list:
  # 1. Manifest without a name in metadata: auto-generate using release name, kind, and index.
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: list-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: list-app
      template:
        metadata:
          labels:
            app: list-app
        spec:
          containers:
            - name: list-container
              image: busybox
              command: ["sleep", "3600"]

  # 2. Manifest with metadata that explicitly provides a name.
  - apiVersion: v1
    kind: Service
    metadata:
      name: service-from-list
      labels:
        app: list-app
    spec:
      selector:
        app: list-app
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 80

  # 3. Manifest without any metadata section: will be merged with generated name.
  - apiVersion: v1
    kind: ConfigMap
    data:
      config.yaml: |
        key: value
        list:
          - a
          - b

  # 4. Manifest with an empty metadata block: should fill in the generated name.
  - apiVersion: v1
    kind: Secret
    metadata: {}
    type: Opaque
    data:
      username: dXNlcm5hbWU= # base64 encoded 'username'
      password: cGFzc3dvcmQ= # base64 encoded 'password'
