ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  enableProxyProtocol: true
gatewayAPI:
  enabled: true
  enableProxyProtocol: true
operator:
  replicas: 1
hubble:
  relay:
    enabled: true
  ui:
    enabled: true

