repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: ~7.8.0
    values:
      - values/argocd-values.yaml
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: ~v1.17.0
    values:
      - values/cert-manager-values.yaml
