version: "3"

dotenv: [".local.env", ".env"]

includes:
  env:
    taskfile: taskfiles/_env.yml
  k8s:
    taskfile: taskfiles/_k8s.yml
  rust:
    taskfile: taskfiles/_rust.yml
    flatten: true

tasks:
  default:
    desc: Show all available tasks
    cmd: task --list-all

  cargo:check: cargo watch -x check
  cargo:watch: >-
    mirrord exec -f .mirrord/mirrord.json -- cargo watch
    --no-vcs-ignores -w target/debug
    -x 'run'
  cargo:dev:
    deps:
      - cargo:check
      - cargo:watch
