dex:
  enabled: false
notifications:
  enabled: false
configs:
  params:
    server:
      insecure: true
  cmp:
    create: true
    plugins:
      helmfile:
        version: v0.171.0
        init:
          command: helmfile
          args:
            - init
            - --force
        discover:
          filename: helmfile.yaml
        generate:
          command: helmfile
          args:
            - template
            - --namespace $ARGOCD_APP_NAMESPACE