list:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: kubeplane
      namespace: argocd
    spec:
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      destinations:
        - namespace: "*"
          server: "*"
      sourceRepos:
        - "*"
  - apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: kubeplane
      namespace: argocd
    spec:
      goTemplate: true
      goTemplateOptions: ["missingkey=error"]
      generators:
        - git:
            repoURL: https://github.com/audacioustux/kubeplane.git
            revision: HEAD
            directories:
              - path: apps/*
      template:
        metadata:
          name: "{{.path.basename}}"
          annotations:
            argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
        spec:
          project: "kubeplane"
          source:
            repoURL: https://github.com/audacioustux/kubeplane.git
            targetRevision: HEAD
            path: "{{.path.path}}"
          destination:
            server: https://kubernetes.default.svc
            namespace: "{{.path.basename}}"
          syncPolicy:
            syncOptions:
              - CreateNamespace=true
              - PruneLast=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
              - FailOnSharedResource=true
            automated:
              prune: true
              selfHeal: true
