{{- $releaseName := .Release.Name }}

{{- range $key, $manifest := .Values.map }}
  {{- $metadata := dict "name" $key }}
  {{- if $manifest.metadata }}
    {{- $metadata = merge $manifest.metadata (dict "name" ($manifest.metadata.name | default $key)) }}
  {{- end }}
  {{- $finalManifest := merge $manifest (dict "metadata" $metadata) }}
{{ toYaml $finalManifest }}
---
{{- end }}

{{- range $index, $manifest := .Values.list }}
  {{- $manifestStr := printf "%s" (toJson $manifest) }}
  {{- $defaultName := printf "%s-%s" (trunc 24 $releaseName) (sha1sum $manifestStr | trunc 10) }}
  {{- $metadata := dict "name" $defaultName }}
  {{- if $manifest.metadata }}
    {{- $metadata = merge $manifest.metadata (dict "name" ($manifest.metadata.name | default $defaultName)) }}
  {{- end }}
  {{- $finalManifest := merge $manifest (dict "metadata" $metadata) }}
{{ toYaml $finalManifest }}
---
{{- end }}
