services:
  devbox:
    build: .
    volumes:
      - ../..:/workspaces:cached,rw
      - docker-certs:/certs:ro
      - nix-store:/nix/store
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client

  docker:
    image: docker:dind
    restart: unless-stopped
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        rm -f /var/run/docker.pid /var/run/docker/containerd/containerd.pid
        dockerd-entrypoint.sh
    privileged: true
    volumes:
      - docker-certs:/certs
      - docker-storage:/var/lib/docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    network_mode: service:devbox

volumes:
  docker-certs:
  docker-storage:
  nix-store:
