# A flat map of manifests keyed by a unique identifier. The key is used as the resource name if metadata.name is not provided.
map: {}

# A list of manifests. If metadata.name is not provided, a generated name of the form: {RELEASE-NAME}{24}-{sha1sum({manifest})}{10} is used.
list: []
