# -------------------------------------------------------------------
# map:
# A flat map of manifests.
#
# Users can add manifests to this map. If metadata.name is not provided,
# the key is used as the name.
#
# Example:
# map:
#   my-app:
#     apiVersion: apps/v1
#     kind: Deployment
#     spec:
#       replicas: 3
#       selector:
#         matchLabels:
#           app: my-app
#       template:
#         metadata:
#           labels:
#             app: my-app
#         spec:
#           containers:
#             - name: my-container
#               image: nginx:latest
#
#   custom-service:
#     apiVersion: v1
#     kind: Service
#     metadata:
#       name: explicit-service-name
#       labels:
#         app: my-app
#     spec:
#       selector:
#         app: my-app
#       ports:
#         - protocol: TCP
#           port: 80
#           targetPort: 80
#
#   my-config:
#     apiVersion: v1
#     kind: ConfigMap
#     metadata:
#       labels:
#         app: test
#     data:
#       key1: value1
#
# -------------------------------------------------------------------
map: {}

# -------------------------------------------------------------------
# list:
# A list of manifests.
#
# Users can add manifests to this list. If metadata.name is not provided,
# a generated name of the form: {RELEASE-NAME}-{sha1sum({manifest})} is used.
#
# Example:
# list:
# - apiVersion: apps/v1
#   kind: Deployment
#   spec:
#     replicas: 3
#     selector:
#       matchLabels:
#         app: my-app
#     template:
#       metadata:
#         labels:
#           app: my-app
#       spec:
#         containers:
#           - name: my-container
#             image: nginx:latest
#
# - apiVersion: v1
#   kind: Service
#   metadata:
#     name: explicit-service-name
#     labels:
#       app: my-app
#   spec:
#     selector:
#       app: my-app
#     ports:
#       - protocol: TCP
#         port: 80
#         targetPort: 80
#
# - apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     labels:
#       app: test
#   data:
#     key1: value1
list: []
