name: Helmfile Render
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push changes
      pull-requests: write # Needed to create PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render Helm templates
        uses: helmfile/helmfile-action@v2
        with:
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: template --output-dir-template rendered/{{.Release.Name}}

      - name: Commit rendered files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b update-rendered-templates
          git add rendered/
          git commit -m "Update rendered Helm templates"
          git push origin update-rendered-templates

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update rendered Helm templates

            * Triggered by ${{ github.event_name }} to ${{ github.ref }}
          delete-branch: true
