name: Helmfile Render
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push changes
      pull-requests: write # Needed to create PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render Helm templates
        uses: helmfile/helmfile-action@v2
        with:
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: template --output-dir-template rendered/{{.Release.Name}}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[Helmfile] Update rendered Helm templates"
          title: "[Helmfile] Merge rendered Helm templates"
          body: |
            > Triggered by ${{ github.event_name }} to ${{ github.ref }}
          branch: helmfile/rendered
          delete-branch: true
